apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blogs-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: blogsite.live
      http:
        paths:
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: todo-srv
                port:
                  number: 3000
